name: Renv433
channels:
  - conda-forge
dependencies:
  - r-base=4.3.3
  - r-xts
  - r-zoo
  - r-forecast
  - r-glmnet
  - r-quantmod
  - r-wavelets
  - r-rmarkdown
  - r-knitr
  - r-dplyr
  - r-tidyr
  - r-stringr
  - r-purrr
  - r-murphydiagram
